$e = [char]27
$rose = "$e[38;2;229;107;138m"
$heart = "$e[38;2;255;105;150m"
$soft = "$e[38;2;245;225;232m"
$dim = "$e[38;2;170;130;145m"
$off = "$e[0m"

Clear-Host
Write-Host ""
Write-Host "${heart}              .:::.           .:::.${off}"
Write-Host "${heart}            .:::::::.       .:::::::.${off}"
Write-Host "${heart}           :::::::::::     :::::::::::${off}"
Write-Host "${heart}           :::::::::::::::::::::::::${off}"
Write-Host "${heart}            ':::::::::::::::::::::'${off}"
Write-Host "${heart}              ':::::::::::::::::'${off}"
Write-Host "${heart}                ':::::::::::::'${off}"
Write-Host "${heart}                  ':::::::::'${off}"
Write-Host "${heart}                    ':::::'${off}"
Write-Host "${heart}                      ':'${off}"
Write-Host ""
Write-Host "${rose}    __  ______________  ____  _____${off}"
Write-Host "${rose}    \ \/ / ____/ ___/ / / / / /   |${off}"
Write-Host "${rose}     \  / __/  \__ \/ /_/ / / /| |${off}"
Write-Host "${rose}     / / /___ ___/ / __  / / ___ |${off}"
Write-Host "${rose}    /_/\____/_/  /_/_/ /_/_/_/  |_|${off}"
Write-Host ""
Write-Host "${dim}   ==========================================${off}"
Write-Host "${soft}          overlay pret  ·  reste ouvert${off}"
Write-Host "${dim}        OBS  →  http://127.0.0.1:7689/${off}"
Write-Host "${dim}   ==========================================${off}"
Write-Host ""
